services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: tecamac
      POSTGRES_USER: tecamac_user
      POSTGRES_PASSWORD: tecamac_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: